SELECT * FROM employees;
-- reads all columns from the table

SELECT * FROM departments;
-- reads all column from departments table

SELECT  first_name From employees;

SELECT CITY FROM LOCATIONS;
-- display city names

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;
-- DISPLAY FIRST NAME, LAST NAME, SALARY,

SELECT  STREET_ADDRESS,POSTAL_CODE FROM LOCATIONS;
-- GET ME STREET ADDRESS AND POSTAL CODE

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES
-- DISTINCT REMOVES THE DUPLICATES